# Disable the "core" laravel plugins
disablePlugins:
  - lando-laravel

# Make sure we are dogfooding this plugin for testing purposes
plugins:
  "@lando/laravel": /home/runner/work/laravel/laravel

# Disable metrics reporting
stats:
  - report: false
    url: https://metrics.lando.dev
